[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700
username=dummy
password=dummy

[supervisord]
nodaemon=false
user=root
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
username=dummy
password=dummy

; -----------------------------------------------------
; PROGRAM: PHP-FPM
; -----------------------------------------------------
[program:php-fpm]
command=/usr/sbin/php-fpm8.1 -F
autostart=true
autorestart=true
priority=10

; -----------------------------------------------------
; PROGRAM: NGINX
; -----------------------------------------------------
[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20
